---
title: "sims_workflow"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Define basic scenario set-up

```{r}

#Number of sites in the landscape
NSites <- 8

#Number of species in the regional pool
NSpecies <- 4

#Number of time points
NYears <- 5

```

Define occupancy settings

```{r}

#Define average occupancy of species
OccProb <- rep(0.5,NSpecies)

#Define average habitat quality of each site
Scovariate <- rnorm(NSites)

#Define spatial quality effects
Seffects <- rep(0,NSpecies)

#Define time trend
Tcovariate <- 1:NYears

#Define spatial quality effects
Teffects <- rep(0,NSpecies)

```

Define sampling effects

```{r}

#Number of visits to each site within each year
NVisits <- 4

#Define average detection probability
DetProb <- 0.5

```


Identify focal species

```{r}

focalSpecies=1

```


Load in functions

```{r}

source('C:/Users/db40fysa/Nextcloud/sMon-Analyses/MoreRangeChangeSims/R/getOccuHistory.R')
source('C:/Users/db40fysa/Nextcloud/sMon-Analyses/MoreRangeChangeSims/R/getRepeatVisits.R')
source('C:/Users/db40fysa/Nextcloud/sMon-Analyses/MoreRangeChangeSims/R/getSpartaFormat.R')
source('C:/Users/db40fysa/Nextcloud/sMon-Analyses/MoreRangeChangeSims/R/getBugsData.R')
source('C:/Users/db40fysa/Nextcloud/sMon-Analyses/MoreRangeChangeSims/R/runModel.R')

```

Run the simulation steps

```{r}

#Simulate the occurrences
runSims <- function(x){
  Occ <- getOccuHistory(occProb = OccProb, spatialbeta=Seffects, spatialcovariates=Scovariate,
                      temporalbeta=Teffects, temporalcovariates=Tcovariate)
  Obs <- getRepeatVisits(Occ=Occ, NVisits=NVisits, DetProb = DetProb)
  modelData <- getSpartaFormat(Obs,focalSpecies=focalSpecies)
  bugs.data <- getBugsData(modelData)
  modelSummary <- runModel(bugs.data,modelData,focalSpecies)
  return(modelSummary)
}

```

Replicate the simulation 500 times

```{r}

out <- replicate(100,runSims(),simplify=FALSE)

```


Get simulation summaries

```{r}

getModelSummaries <- function(out){
  
  outCombined <- do.call(rbind,out)
  outSummaries <- ddply(outCombined,.(Param),
                        summarise,
                        meanValue = mean(mean))
  
  return(outSummaries)
  
}


```
